#!/bin/sh
# Create a custom keychain
security create-keychain -p gitlab "$APP_NAME.keychain"

# Add it to the list
security list-keychains -s "$APP_NAME.keychain"

# Make the custom keychain default, so xcodebuild will use it for signing
security default-keychain -s "$APP_NAME.keychain"

# Unlock the keychain
security unlock-keychain -p gitlab "$APP_NAME.keychain"

# Set keychain timeout to 1 hour for long builds
# see http://www.egeek.me/2013/02/23/jenkins-and-xcode-user-interaction-is-not-allowed/
security set-keychain-settings -t 3600 -l "$APP_NAME.keychain"

# Add certificates to keychain and allow codesign to access them
security import $APP_CERT -k "$APP_NAME.keychain" -T /usr/bin/codesign
security import $APP_CERT -k "$APP_NAME.keychain" -T /usr/bin/codesign
security import $APP_KEY -k "$APP_NAME.keychain" -P $KEY_PASSWORD -T /usr/bin/codesign

# Put the provisioning profile in place
mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
cp $PROFILE ~/Library/MobileDevice/Provisioning\ Profiles/
