#!/bin/sh
INSTALLED_PROVISIONING_PROFILE="$HOME/Library/MobileDevice/Provisioning Profiles/$PROVISIONING_PROFILE_NAME.mobileprovision"
OUTPUTDIR="$PWD/build/Release-iphoneos"

echo "Creating IPA"
xcrun -log -sdk iphoneos PackageApplication "$OUTPUTDIR/$APP_NAME.app" -o "$OUTPUTDIR/$APP_NAME.ipa" -sign "$DEVELOPER_NAME" -embed "$INSTALLED_PROVISIONING_PROFILE"
