#!/bin/sh
security delete-keychain "$APP_NAME.keychain"
if [ -z "$PROVISIONING_PROFILE" ]; then
  echo "Skipping profile install";
else
  rm -f "~/Library/MobileDevice/Provisioning Profiles/$PROVISIONING_PROFILE_NAME.mobileprovision"
fi
